// This file is auto-generated by @hey-api/openapi-ts

export const ActivityActionSchema = {
    type: 'string',
    enum: [
        'task_created',
        'task_changed',
        'tasks_bulk_changed',
        'task_completed',
        'task_reopened',
        'task_status_changed',
        'task_deleted',
        'task_restored',
        'task_moved',
        'task_assigned',
        'task_unassigned',
        'project_created',
        'project_changed',
        'project_deleted',
        'project_restored',
        'comment_added',
        'comment_edited',
        'comment_deleted',
        'attachment_added',
        'attachment_deleted',
        'tag_created',
        'tag_renamed',
        'tag_deleted',
        'tag_merged'
    ],
    title: 'ActivityAction',
    description: 'Everything the activity log records (FR-10.3).'
} as const;

export const ActivityEntityTypeSchema = {
    type: 'string',
    enum: [
        'task',
        'project',
        'comment',
        'attachment',
        'tag'
    ],
    title: 'ActivityEntityType'
} as const;

export const ActivityEntriesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ActivityEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ActivityEntriesPublic'
} as const;

export const ActivityEntryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        action: {
            $ref: '#/components/schemas/ActivityAction'
        },
        entity_type: {
            $ref: '#/components/schemas/ActivityEntityType'
        },
        entity_id: {
            type: 'string',
            format: 'uuid',
            title: 'Entity Id'
        },
        actor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor Id'
        },
        actor_bot_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor Bot User Id'
        },
        actor_bot_user_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor Bot User Name'
        },
        deletion_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deletion Id'
        },
        details: {
            additionalProperties: true,
            type: 'object',
            title: 'Details'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        entity_exists: {
            type: 'boolean',
            title: 'Entity Exists'
        },
        entity_project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Project Id'
        },
        restorable: {
            type: 'boolean',
            title: 'Restorable',
            default: false
        }
    },
    type: 'object',
    required: [
        'id',
        'action',
        'entity_type',
        'entity_id',
        'details',
        'entity_exists'
    ],
    title: 'ActivityEntryPublic'
} as const;

export const ActivityKindSchema = {
    type: 'string',
    enum: [
        'completed',
        'created',
        'changed',
        'deleted',
        'comments',
        'tags'
    ],
    title: 'ActivityKind',
    description: 'How a reader groups the log\'s actions in order to narrow it.\n\nCoarser than `ActivityAction` on purpose: someone asks the log what they\nfinished, filed or threw away — not which of two dozen action names an\nentry happens to carry. The groups do not overlap, so an entry answers to\nexactly one of them and a reader never meets the same change twice.\n\nThe grouping is the server\'s rather than a set of actions the client\nsends, because `COMPLETED` is not a set of actions at all: closing tasks\nin a batch writes one `TASKS_BULK_CHANGED` entry naming the new status,\nnot a completion per task, so the group has to read that entry\'s details.'
} as const;

export const ActivityOrderSchema = {
    type: 'string',
    enum: [
        'newest',
        'oldest'
    ],
    title: 'ActivityOrder',
    description: 'Which end of the log a read starts from (FR-10.10).'
} as const;

export const AttachmentPublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        content_type: {
            type: 'string',
            maxLength: 255,
            title: 'Content Type'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'filename',
        'content_type',
        'size',
        'id',
        'task_id'
    ],
    title: 'AttachmentPublic'
} as const;

export const AttachmentsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/AttachmentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'AttachmentsPublic'
} as const;

export const Body_attachments_upload_attachmentSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_attachments-upload_attachment'
} as const;

export const BotPermissionsSchema = {
    properties: {
        create_tasks: {
            type: 'boolean',
            title: 'Create Tasks',
            default: false
        },
        read_tasks: {
            type: 'boolean',
            title: 'Read Tasks',
            default: false
        },
        update_tasks: {
            type: 'boolean',
            title: 'Update Tasks',
            default: false
        },
        delete_tasks: {
            type: 'boolean',
            title: 'Delete Tasks',
            default: false
        },
        add_comments: {
            type: 'boolean',
            title: 'Add Comments',
            default: false
        },
        create_tags: {
            type: 'boolean',
            title: 'Create Tags',
            default: false
        }
    },
    type: 'object',
    title: 'BotPermissions',
    description: 'What a bot user may do inside the projects of its scope (FR-08.9,\nFR-08.10).\n\nOnly what can be granted is here. What a bot can never do — anything on\nprojects, editing or deleting comments, renaming or deleting tags — has no\nfield to set to false: the endpoints for it take a human caller, so a bot\ncannot reach them at all. Reading tags needs no field either: every bot\nuser reads its owner\'s whole tag vocabulary, whatever its scope\n(ADR-0003).'
} as const;

export const BotScopeSchema = {
    properties: {
        project_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Project Ids'
        },
        permissions: {
            $ref: '#/components/schemas/BotPermissions'
        }
    },
    type: 'object',
    required: [
        'project_ids',
        'permissions'
    ],
    title: 'BotScope',
    description: 'Where a bot user may act and what it may do there.\n\nThe projects are always named one by one: there is no value meaning "all\nprojects" (FR-08.6), so a project created tomorrow is never in the scope\nof a bot set up today.'
} as const;

export const BotTokenIssueSchema = {
    properties: {
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        }
    },
    type: 'object',
    title: 'BotTokenIssue',
    description: 'How a token is issued: with an expiry, or none to last until revoked.'
} as const;

export const BotTokenIssuedSchema = {
    properties: {
        bot_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bot User Id'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        }
    },
    type: 'object',
    required: [
        'bot_user_id',
        'token'
    ],
    title: 'BotTokenIssued',
    description: 'The one response that carries a bot user\'s token (FR-08.13).'
} as const;

export const BotUserCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        scope: {
            $ref: '#/components/schemas/BotScope'
        }
    },
    type: 'object',
    required: [
        'name',
        'scope'
    ],
    title: 'BotUserCreate'
} as const;

export const BotUserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        scope: {
            $ref: '#/components/schemas/BotScope'
        },
        deleted: {
            type: 'boolean',
            title: 'Deleted',
            default: false
        },
        deleted_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deleted At'
        },
        assigned_task_count: {
            type: 'integer',
            title: 'Assigned Task Count',
            default: 0
        },
        has_token: {
            type: 'boolean',
            title: 'Has Token'
        },
        token_issued_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Issued At'
        },
        token_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Expires At'
        },
        token_last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Last Used At'
        },
        token_revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Revoked At'
        },
        webhooks: {
            $ref: '#/components/schemas/BotWebhooks'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'scope',
        'has_token',
        'webhooks'
    ],
    title: 'BotUserPublic'
} as const;

export const BotUserRefSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        deleted: {
            type: 'boolean',
            title: 'Deleted'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'deleted'
    ],
    title: 'BotUserRef',
    description: 'A bot user as a task or comment names it: the one it is assigned to, or\nthe one that wrote it. A deleted bot user stays on what it was given and\nwhat it wrote (FR-08.19, FR-08.21), marked deleted.'
} as const;

export const BotUserUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        scope: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BotScope'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'BotUserUpdate',
    description: 'A change to a bot user: its name, its scope, or both. A scope is sent\nwhole — its projects and its permissions — and replaces the one the bot\nuser had, so what is granted is always exactly what the user last saw.'
} as const;

export const BotUsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/BotUserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'BotUsersPublic'
} as const;

export const BotWebhooksSchema = {
    properties: {
        task: {
            $ref: '#/components/schemas/WebhookPublic'
        },
        comment: {
            $ref: '#/components/schemas/WebhookPublic'
        },
        has_secret: {
            type: 'boolean',
            title: 'Has Secret'
        }
    },
    type: 'object',
    required: [
        'task',
        'comment',
        'has_secret'
    ],
    title: 'BotWebhooks'
} as const;

export const BulkResultSchema = {
    properties: {
        updated: {
            type: 'integer',
            title: 'Updated',
            default: 0
        },
        deleted: {
            type: 'integer',
            title: 'Deleted',
            default: 0
        }
    },
    type: 'object',
    title: 'BulkResult',
    description: 'How many tasks one act changed.'
} as const;

export const CommentCreateSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 10000,
            minLength: 1,
            title: 'Body'
        }
    },
    type: 'object',
    required: [
        'body'
    ],
    title: 'CommentCreate'
} as const;

export const CommentPublicSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 10000,
            title: 'Body'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        author_bot_user: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BotUserRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'body',
        'id',
        'task_id'
    ],
    title: 'CommentPublic'
} as const;

export const CommentUpdateSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 10000,
            minLength: 1,
            title: 'Body'
        }
    },
    type: 'object',
    required: [
        'body'
    ],
    title: 'CommentUpdate'
} as const;

export const CommentsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CommentsPublic'
} as const;

export const ConfirmationSchema = {
    properties: {
        confirmation: {
            additionalProperties: true,
            type: 'object',
            title: 'Confirmation'
        }
    },
    type: 'object',
    required: [
        'confirmation'
    ],
    title: 'Confirmation',
    description: 'A fresh assertion with one of the caller\'s own passkeys, answering a\nconfirmation challenge (FR-12.7, FR-12.16).'
} as const;

export const DeliveryStateSchema = {
    type: 'string',
    enum: [
        'pending',
        'delivered',
        'failed'
    ],
    title: 'DeliveryState'
} as const;

export const DueDateScopeSchema = {
    type: 'string',
    enum: [
        'this_occurrence',
        'this_and_following'
    ],
    title: 'DueDateScope',
    description: 'What moving the due date of an open recurring occurrence means for the rest\nof its series.\n\nThere is no default: a client that changes the date without saying which\none is refused, so a series is never rescheduled by omission (FR-01.17).'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const PasskeyCredentialSchema = {
    properties: {
        credential: {
            additionalProperties: true,
            type: 'object',
            title: 'Credential'
        }
    },
    type: 'object',
    required: [
        'credential'
    ],
    title: 'PasskeyCredential',
    description: 'The browser\'s answer to a passkey ceremony, as WebAuthn\'s\n`PublicKeyCredential.toJSON()` gives it.'
} as const;

export const PasskeyPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'created_at',
        'last_used_at'
    ],
    title: 'PasskeyPublic'
} as const;

export const PasskeyRenameSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'PasskeyRename'
} as const;

export const PasskeysPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/PasskeyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'PasskeysPublic'
} as const;

export const PrivateRecoveryCodeSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        }
    },
    type: 'object',
    required: [
        'email'
    ],
    title: 'PrivateRecoveryCode'
} as const;

export const PrivateSessionSchema = {
    properties: {
        user: {
            $ref: '#/components/schemas/UserPublic'
        },
        access_token: {
            type: 'string',
            title: 'Access Token'
        }
    },
    type: 'object',
    required: [
        'user',
        'access_token'
    ],
    title: 'PrivateSession'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        }
    },
    type: 'object',
    required: [
        'email'
    ],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_inbox: {
            type: 'boolean',
            title: 'Is Inbox'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        task_count: {
            type: 'integer',
            title: 'Task Count',
            default: 0
        },
        open_count: {
            type: 'integer',
            title: 'Open Count',
            default: 0
        },
        overdue_count: {
            type: 'integer',
            title: 'Overdue Count',
            default: 0
        },
        backlog_count: {
            type: 'integer',
            title: 'Backlog Count',
            default: 0
        },
        review_count: {
            type: 'integer',
            title: 'Review Count',
            default: 0
        },
        done_count: {
            type: 'integer',
            title: 'Done Count',
            default: 0
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'name',
        'id',
        'is_inbox',
        'is_archived'
    ],
    title: 'ProjectPublic'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ProjectsPublic'
} as const;

export const RecoveryCodeIssuedSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: [
        'code',
        'expires_at'
    ],
    title: 'RecoveryCodeIssued'
} as const;

export const RecoveryStartSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        code: {
            type: 'string',
            maxLength: 64,
            title: 'Code'
        }
    },
    type: 'object',
    required: [
        'email',
        'code'
    ],
    title: 'RecoveryStart'
} as const;

export const RecurrenceSchema = {
    properties: {
        frequency: {
            $ref: '#/components/schemas/RecurrenceFrequency'
        },
        interval_days: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Interval Days'
        }
    },
    type: 'object',
    required: [
        'frequency'
    ],
    title: 'Recurrence',
    description: 'How often a recurring task comes back: a fixed interval, never tied to when\nan occurrence happened to be done (FR-01.13, FR-01.15).'
} as const;

export const RecurrenceFrequencySchema = {
    type: 'string',
    enum: [
        'daily',
        'weekly',
        'monthly',
        'every_n_days'
    ],
    title: 'RecurrenceFrequency'
} as const;

export const RegistrationStartSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: [
        'email'
    ],
    title: 'RegistrationStart'
} as const;

export const SortOrderSchema = {
    type: 'string',
    enum: [
        'asc',
        'desc'
    ],
    title: 'SortOrder'
} as const;

export const SubtaskCompletionSchema = {
    type: 'string',
    enum: [
        'leave_uncompleted',
        'complete'
    ],
    title: 'SubtaskCompletion',
    description: 'What a request that moves a task to done says about its open subtasks.\n\nSending neither value is not a default: the request is refused, so a client\nnever closes a parent without saying what happens below it (FR-02.6,\nFR-02.7). `complete` moves the subtasks to done; `leave_uncompleted` leaves\neach in the open status it has.'
} as const;

export const TagCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'TagCreate'
} as const;

export const TagDuplicateDismissSchema = {
    properties: {
        tag_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 2,
            title: 'Tag Ids'
        }
    },
    type: 'object',
    required: [
        'tag_ids'
    ],
    title: 'TagDuplicateDismiss',
    description: 'Every member of the group to stop offering, and nothing else.'
} as const;

export const TagDuplicateGroupSchema = {
    properties: {
        tags: {
            items: {
                $ref: '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags'
        }
    },
    type: 'object',
    required: [
        'tags'
    ],
    title: 'TagDuplicateGroup',
    description: 'Tags whose names differ only in form: a suggestion to merge them.'
} as const;

export const TagDuplicateGroupsSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/TagDuplicateGroup'
            },
            type: 'array',
            title: 'Data'
        }
    },
    type: 'object',
    required: [
        'data'
    ],
    title: 'TagDuplicateGroups'
} as const;

export const TagMergeSchema = {
    properties: {
        source_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Source Ids'
        }
    },
    type: 'object',
    required: [
        'source_ids'
    ],
    title: 'TagMerge',
    description: 'The tags to fold into the one the merge is addressed to.'
} as const;

export const TagMergePreviewSchema = {
    properties: {
        task_count: {
            type: 'integer',
            title: 'Task Count'
        },
        archived_task_count: {
            type: 'integer',
            title: 'Archived Task Count'
        }
    },
    type: 'object',
    required: [
        'task_count',
        'archived_task_count'
    ],
    title: 'TagMergePreview',
    description: 'What a merge would move: the tasks carrying any of the sources, each\ncounted once, live and archived apart (FR-01.27).'
} as const;

export const TagPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_count: {
            type: 'integer',
            title: 'Task Count',
            default: 0
        },
        archived_task_count: {
            type: 'integer',
            title: 'Archived Task Count',
            default: 0
        },
        created_by_bot_user: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BotUserRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'name',
        'id'
    ],
    title: 'TagPublic'
} as const;

export const TagUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'TagUpdate'
} as const;

export const TagsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'TagsPublic'
} as const;

export const TaskBulkDeleteSchema = {
    properties: {
        task_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 500,
            minItems: 1,
            title: 'Task Ids'
        },
        delete_subtasks: {
            type: 'boolean',
            title: 'Delete Subtasks',
            default: false
        }
    },
    type: 'object',
    required: [
        'task_ids'
    ],
    title: 'TaskBulkDelete',
    description: 'One deletion event over several tasks, restorable as the one act it was.'
} as const;

export const TaskBulkUpdateSchema = {
    properties: {
        task_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 500,
            minItems: 1,
            title: 'Task Ids'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        subtasks: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SubtaskCompletion'
                },
                {
                    type: 'null'
                }
            ]
        },
        priority: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        add_tags: {
            items: {
                type: 'string',
                maxLength: 50,
                minLength: 1
            },
            type: 'array',
            title: 'Add Tags',
            default: []
        },
        remove_tags: {
            items: {
                type: 'string',
                maxLength: 50,
                minLength: 1
            },
            type: 'array',
            title: 'Remove Tags',
            default: []
        }
    },
    type: 'object',
    required: [
        'task_ids'
    ],
    title: 'TaskBulkUpdate',
    description: 'One set of changes for many tasks: the single-task update, plus the tasks\nit applies to.\n\n`add_tags` and `remove_tags` rather than `tags`: a batch adds a label to a\nselection or takes one off it, and replacing every task\'s tags wholesale\nwould destroy what each of them already carried.'
} as const;

export const TaskCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string',
                maxLength: 50,
                minLength: 1
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        recurrence: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Recurrence'
                },
                {
                    type: 'null'
                }
            ]
        },
        status: {
            $ref: '#/components/schemas/TaskStatus',
            default: 'backlog'
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'TaskCreate'
} as const;

export const TaskHandoverSchema = {
    properties: {
        bot_user: {
            $ref: '#/components/schemas/BotUserRef'
        },
        at: {
            type: 'string',
            format: 'date-time',
            title: 'At'
        }
    },
    type: 'object',
    required: [
        'bot_user',
        'at'
    ],
    title: 'TaskHandover',
    description: 'How a task came to be in Review when a bot user put it there: which bot\nuser handed its work over, and when (ADR-0008). Read off the activity\nlog, so it names a deleted bot user as it was called.'
} as const;

export const TaskPrioritySchema = {
    type: 'string',
    enum: [
        'P1',
        'P2',
        'P3',
        'P4'
    ],
    title: 'TaskPriority'
} as const;

export const TaskPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        status: {
            $ref: '#/components/schemas/TaskStatus'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        assignee_bot_user: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BotUserRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        reporter_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reporter Id'
        },
        reporter_bot_user: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BotUserRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        recurrence: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Recurrence'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        subtask_count: {
            type: 'integer',
            title: 'Subtask Count',
            default: 0
        },
        subtasks_done: {
            type: 'integer',
            title: 'Subtasks Done',
            default: 0
        },
        handover: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskHandover'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'title',
        'id',
        'status',
        'project_id'
    ],
    title: 'TaskPublic'
} as const;

export const TaskSortSchema = {
    type: 'string',
    enum: [
        'due_date',
        'priority',
        'created_at'
    ],
    title: 'TaskSort',
    description: 'How a task list can be ordered, and which way round each one naturally\nruns when the request names no direction (FR-06.4).\n\nDue date means soonest first and priority means P1 first, because that is\nthe work to reach for. Creation means newest first, because the reason to\norder by it is to see what has just arrived.'
} as const;

export const TaskStatusSchema = {
    type: 'string',
    enum: [
        'backlog',
        'todo',
        'in_progress',
        'review',
        'waiting',
        'done'
    ],
    title: 'TaskStatus',
    description: 'Where a task stands (FR-01.4). Six fixed values rather than user-defined\nones (ADR-0004, ADR-0008): every rule in the product only needs to know\nwhether a task is open or done, and the five open values tell apart\nwhether the work is decided on and who holds the next move. Declared in\nthe order the interface lists them.\n\nA new task starts in `backlog`. A bot user hands finished work over by\nmoving it to `review` and assigning it to the owner; entering review\ndoes not change the assignee on its own (FR-01.4a).'
} as const;

export const TaskUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        maxLength: 50,
                        minLength: 1
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        subtasks: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SubtaskCompletion'
                },
                {
                    type: 'null'
                }
            ]
        },
        recurrence: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Recurrence'
                },
                {
                    type: 'null'
                }
            ]
        },
        due_date_scope: {
            anyOf: [
                {
                    $ref: '#/components/schemas/DueDateScope'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'TaskUpdate'
} as const;

export const TasksPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/TaskPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'TasksPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UserListedSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        passkey_count: {
            type: 'integer',
            title: 'Passkey Count'
        },
        last_sign_in_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Sign In At'
        }
    },
    type: 'object',
    required: [
        'email',
        'id',
        'passkey_count'
    ],
    title: 'UserListed',
    description: 'An account as the superuser\'s list shows it: the account fields, how many\npasskeys it holds, and when one of them last signed it in (FR-09.2). Nothing\nabout what the account holds or does (FR-10.7).'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserListed'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const WebhookDeliveryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        event: {
            $ref: '#/components/schemas/WebhookEventType'
        },
        attempted_at: {
            type: 'string',
            format: 'date-time',
            title: 'Attempted At'
        },
        success: {
            type: 'boolean',
            title: 'Success'
        },
        state: {
            $ref: '#/components/schemas/DeliveryState'
        },
        attempts: {
            type: 'integer',
            title: 'Attempts'
        },
        status_code: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status Code'
        },
        error: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error'
        },
        duration_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration Ms'
        },
        next_attempt_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Next Attempt At'
        }
    },
    type: 'object',
    required: [
        'id',
        'event',
        'attempted_at',
        'success',
        'state',
        'attempts'
    ],
    title: 'WebhookDeliveryPublic',
    description: 'A delivery as the owner sees it: when it was attempted, whether it\nsucceeded, and the response status or the error (FR-11.11).'
} as const;

export const WebhookEventTypeSchema = {
    type: 'string',
    enum: [
        'task.ready',
        'comment.added',
        'test'
    ],
    title: 'WebhookEventType',
    description: 'What a delivery says happened (FR-11.8).'
} as const;

export const WebhookKindSchema = {
    type: 'string',
    enum: [
        'task',
        'comment'
    ],
    title: 'WebhookKind',
    description: 'The bot user\'s two webhooks (FR-11.1).'
} as const;

export const WebhookPublicSchema = {
    properties: {
        url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        last_delivery: {
            anyOf: [
                {
                    $ref: '#/components/schemas/WebhookDeliveryPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'WebhookPublic'
} as const;

export const WebhookSecretIssuedSchema = {
    properties: {
        bot_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bot User Id'
        },
        secret: {
            type: 'string',
            title: 'Secret'
        }
    },
    type: 'object',
    required: [
        'bot_user_id',
        'secret'
    ],
    title: 'WebhookSecretIssued',
    description: 'The one response that carries a regenerated secret (FR-11.9).'
} as const;

export const WebhookSetSchema = {
    properties: {
        bot_user: {
            $ref: '#/components/schemas/BotUserPublic'
        },
        secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret'
        }
    },
    type: 'object',
    required: [
        'bot_user'
    ],
    title: 'WebhookSet',
    description: 'The result of setting a webhook. `secret` is set only when this call\ngenerated it (the bot user\'s first webhook): it is shown once (FR-11.9).'
} as const;

export const WebhookUrlSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 2048,
            title: 'Url'
        }
    },
    type: 'object',
    required: [
        'url'
    ],
    title: 'WebhookUrl',
    description: 'The address a webhook is set to: http or https (FR-11.3).'
} as const;
