// This file is auto-generated by @hey-api/openapi-ts

export const ActivityActionSchema = {
    type: 'string',
    enum: [
        'task_created',
        'task_changed',
        'tasks_bulk_changed',
        'task_completed',
        'task_reopened',
        'task_deleted',
        'task_restored',
        'task_moved',
        'task_assigned',
        'task_unassigned',
        'project_created',
        'project_changed',
        'project_deleted',
        'project_restored',
        'comment_added',
        'comment_edited',
        'comment_deleted',
        'attachment_added',
        'attachment_deleted',
        'tag_created',
        'tag_renamed',
        'tag_deleted',
        'tag_merged'
    ],
    title: 'ActivityAction',
    description: 'Everything the activity log records (FR-10.3).'
} as const;

export const ActivityEntityTypeSchema = {
    type: 'string',
    enum: [
        'task',
        'project',
        'comment',
        'attachment',
        'tag'
    ],
    title: 'ActivityEntityType'
} as const;

export const ActivityEntriesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ActivityEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ActivityEntriesPublic'
} as const;

export const ActivityEntryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        action: {
            $ref: '#/components/schemas/ActivityAction'
        },
        entity_type: {
            $ref: '#/components/schemas/ActivityEntityType'
        },
        entity_id: {
            type: 'string',
            format: 'uuid',
            title: 'Entity Id'
        },
        actor_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor Id'
        },
        actor_bot_user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor Bot User Id'
        },
        actor_bot_user_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actor Bot User Name'
        },
        deletion_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Deletion Id'
        },
        details: {
            additionalProperties: true,
            type: 'object',
            title: 'Details'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        entity_exists: {
            type: 'boolean',
            title: 'Entity Exists'
        },
        entity_project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Entity Project Id'
        },
        restorable: {
            type: 'boolean',
            title: 'Restorable',
            default: false
        }
    },
    type: 'object',
    required: [
        'id',
        'action',
        'entity_type',
        'entity_id',
        'details',
        'entity_exists'
    ],
    title: 'ActivityEntryPublic'
} as const;

export const AttachmentPublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        content_type: {
            type: 'string',
            maxLength: 255,
            title: 'Content Type'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'filename',
        'content_type',
        'size',
        'id',
        'task_id'
    ],
    title: 'AttachmentPublic'
} as const;

export const AttachmentsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/AttachmentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'AttachmentsPublic'
} as const;

export const Body_attachments_upload_attachmentSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: [
        'file'
    ],
    title: 'Body_attachments-upload_attachment'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login-login_access_token'
} as const;

export const BotPermissionsSchema = {
    properties: {
        create_tasks: {
            type: 'boolean',
            title: 'Create Tasks',
            default: false
        },
        read_tasks: {
            type: 'boolean',
            title: 'Read Tasks',
            default: false
        },
        update_tasks: {
            type: 'boolean',
            title: 'Update Tasks',
            default: false
        },
        delete_tasks: {
            type: 'boolean',
            title: 'Delete Tasks',
            default: false
        },
        add_comments: {
            type: 'boolean',
            title: 'Add Comments',
            default: false
        },
        create_tags: {
            type: 'boolean',
            title: 'Create Tags',
            default: false
        }
    },
    type: 'object',
    title: 'BotPermissions',
    description: 'What a bot user may do inside the projects of its scope (FR-08.9,\nFR-08.10).\n\nOnly what can be granted is here. What a bot can never do — anything on\nprojects, editing or deleting comments, renaming or deleting tags — has no\nfield to set to false: the endpoints for it take a human caller, so a bot\ncannot reach them at all. Reading tags needs no field either: every bot\nuser reads its owner\'s whole tag vocabulary, whatever its scope\n(ADR-0003).'
} as const;

export const BotScopeSchema = {
    properties: {
        project_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Project Ids'
        },
        permissions: {
            $ref: '#/components/schemas/BotPermissions'
        }
    },
    type: 'object',
    required: [
        'project_ids',
        'permissions'
    ],
    title: 'BotScope',
    description: 'Where a bot user may act and what it may do there.\n\nThe projects are always named one by one: there is no value meaning "all\nprojects" (FR-08.6), so a project created tomorrow is never in the scope\nof a bot set up today.'
} as const;

export const BotTokenIssueSchema = {
    properties: {
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        }
    },
    type: 'object',
    title: 'BotTokenIssue',
    description: 'How a token is issued: with an expiry, or none to last until revoked.'
} as const;

export const BotTokenIssuedSchema = {
    properties: {
        bot_user_id: {
            type: 'string',
            format: 'uuid',
            title: 'Bot User Id'
        },
        token: {
            type: 'string',
            title: 'Token'
        },
        expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires At'
        }
    },
    type: 'object',
    required: [
        'bot_user_id',
        'token'
    ],
    title: 'BotTokenIssued',
    description: 'The one response that carries a bot user\'s token (FR-08.13).'
} as const;

export const BotUserCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        scope: {
            $ref: '#/components/schemas/BotScope'
        }
    },
    type: 'object',
    required: [
        'name',
        'scope'
    ],
    title: 'BotUserCreate'
} as const;

export const BotUserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        scope: {
            $ref: '#/components/schemas/BotScope'
        },
        deleted: {
            type: 'boolean',
            title: 'Deleted',
            default: false
        },
        has_token: {
            type: 'boolean',
            title: 'Has Token'
        },
        token_issued_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Issued At'
        },
        token_expires_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Expires At'
        },
        token_last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Last Used At'
        },
        token_revoked_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Token Revoked At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'scope',
        'has_token'
    ],
    title: 'BotUserPublic'
} as const;

export const BotUserRefSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        deleted: {
            type: 'boolean',
            title: 'Deleted'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'deleted'
    ],
    title: 'BotUserRef',
    description: 'A bot user as a task or comment names it: the one it is assigned to, or\nthe one that wrote it. A deleted bot user stays on what it was given and\nwhat it wrote (FR-08.19, FR-08.21), marked deleted.'
} as const;

export const BotUserUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        scope: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BotScope'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'BotUserUpdate',
    description: 'A change to a bot user: its name, its scope, or both. A scope is sent\nwhole — its projects and its permissions — and replaces the one the bot\nuser had, so what is granted is always exactly what the user last saw.'
} as const;

export const BotUsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/BotUserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'BotUsersPublic'
} as const;

export const BulkResultSchema = {
    properties: {
        updated: {
            type: 'integer',
            title: 'Updated',
            default: 0
        },
        deleted: {
            type: 'integer',
            title: 'Deleted',
            default: 0
        }
    },
    type: 'object',
    title: 'BulkResult',
    description: 'How many tasks one act changed.'
} as const;

export const CommentCreateSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 10000,
            minLength: 1,
            title: 'Body'
        }
    },
    type: 'object',
    required: [
        'body'
    ],
    title: 'CommentCreate'
} as const;

export const CommentPublicSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 10000,
            title: 'Body'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_id: {
            type: 'string',
            format: 'uuid',
            title: 'Task Id'
        },
        author_bot_user: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BotUserRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'body',
        'id',
        'task_id'
    ],
    title: 'CommentPublic'
} as const;

export const CommentUpdateSchema = {
    properties: {
        body: {
            type: 'string',
            maxLength: 10000,
            minLength: 1,
            title: 'Body'
        }
    },
    type: 'object',
    required: [
        'body'
    ],
    title: 'CommentUpdate'
} as const;

export const CommentsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/CommentPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'CommentsPublic'
} as const;

export const DueDateScopeSchema = {
    type: 'string',
    enum: [
        'this_occurrence',
        'this_and_following'
    ],
    title: 'DueDateScope',
    description: 'What moving the due date of an open recurring occurrence means for the rest\nof its series.\n\nThere is no default: a client that changes the date without saying which\none is refused, so a series is never rescheduled by omission (FR-01.17).'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: [
        'email',
        'password',
        'full_name'
    ],
    title: 'PrivateUserCreate'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ProjectCreate'
} as const;

export const ProjectPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_inbox: {
            type: 'boolean',
            title: 'Is Inbox'
        },
        is_archived: {
            type: 'boolean',
            title: 'Is Archived'
        },
        task_count: {
            type: 'integer',
            title: 'Task Count',
            default: 0
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'name',
        'id',
        'is_inbox',
        'is_archived'
    ],
    title: 'ProjectPublic'
} as const;

export const ProjectUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ProjectUpdate'
} as const;

export const ProjectsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ProjectPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ProjectsPublic'
} as const;

export const RecurrenceSchema = {
    properties: {
        frequency: {
            $ref: '#/components/schemas/RecurrenceFrequency'
        },
        interval_days: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Interval Days'
        }
    },
    type: 'object',
    required: [
        'frequency'
    ],
    title: 'Recurrence',
    description: 'How often a recurring task comes back: a fixed interval, never tied to when\nan occurrence happened to be completed (FR-01.13, FR-01.15).'
} as const;

export const RecurrenceFrequencySchema = {
    type: 'string',
    enum: [
        'daily',
        'weekly',
        'monthly',
        'every_n_days'
    ],
    title: 'RecurrenceFrequency'
} as const;

export const SortOrderSchema = {
    type: 'string',
    enum: [
        'asc',
        'desc'
    ],
    title: 'SortOrder'
} as const;

export const SubtaskCompletionSchema = {
    type: 'string',
    enum: [
        'leave_uncompleted',
        'complete'
    ],
    title: 'SubtaskCompletion',
    description: 'What a completion request says about the task\'s uncompleted subtasks.\n\nSending neither value is not a default: the request is refused, so a client\nnever completes a parent without saying what happens below it (FR-02.6,\nFR-02.7).'
} as const;

export const TagCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'TagCreate'
} as const;

export const TagMergeSchema = {
    properties: {
        source_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Source Ids'
        }
    },
    type: 'object',
    required: [
        'source_ids'
    ],
    title: 'TagMerge',
    description: 'The tags to fold into the one the merge is addressed to.'
} as const;

export const TagMergePreviewSchema = {
    properties: {
        task_count: {
            type: 'integer',
            title: 'Task Count'
        },
        archived_task_count: {
            type: 'integer',
            title: 'Archived Task Count'
        }
    },
    type: 'object',
    required: [
        'task_count',
        'archived_task_count'
    ],
    title: 'TagMergePreview',
    description: 'What a merge would move: the tasks carrying any of the sources, each\ncounted once, live and archived apart (semaputnik/taskly#69).'
} as const;

export const TagPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        task_count: {
            type: 'integer',
            title: 'Task Count',
            default: 0
        },
        archived_task_count: {
            type: 'integer',
            title: 'Archived Task Count',
            default: 0
        }
    },
    type: 'object',
    required: [
        'name',
        'id'
    ],
    title: 'TagPublic'
} as const;

export const TagUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 50,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'TagUpdate'
} as const;

export const TagsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'TagsPublic'
} as const;

export const TaskBulkDeleteSchema = {
    properties: {
        task_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 500,
            minItems: 1,
            title: 'Task Ids'
        },
        delete_subtasks: {
            type: 'boolean',
            title: 'Delete Subtasks',
            default: false
        }
    },
    type: 'object',
    required: [
        'task_ids'
    ],
    title: 'TaskBulkDelete',
    description: 'One deletion event over several tasks, restorable as the one act it was.'
} as const;

export const TaskBulkUpdateSchema = {
    properties: {
        task_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            maxItems: 500,
            minItems: 1,
            title: 'Task Ids'
        },
        completed: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed'
        },
        subtasks: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SubtaskCompletion'
                },
                {
                    type: 'null'
                }
            ]
        },
        priority: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        add_tags: {
            items: {
                type: 'string',
                maxLength: 50,
                minLength: 1
            },
            type: 'array',
            title: 'Add Tags',
            default: []
        },
        remove_tags: {
            items: {
                type: 'string',
                maxLength: 50,
                minLength: 1
            },
            type: 'array',
            title: 'Remove Tags',
            default: []
        }
    },
    type: 'object',
    required: [
        'task_ids'
    ],
    title: 'TaskBulkUpdate',
    description: 'One set of changes for many tasks: the single-task update, plus the tasks\nit applies to.\n\n`add_tags` and `remove_tags` rather than `tags`: a batch adds a label to a\nselection or takes one off it, and replacing every task\'s tags wholesale\nwould destroy what each of them already carried.'
} as const;

export const TaskCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        tags: {
            items: {
                type: 'string',
                maxLength: 50,
                minLength: 1
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        recurrence: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Recurrence'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'TaskCreate'
} as const;

export const TaskPrioritySchema = {
    type: 'string',
    enum: [
        'P1',
        'P2',
        'P3',
        'P4'
    ],
    title: 'TaskPriority'
} as const;

export const TaskPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        completed: {
            type: 'boolean',
            title: 'Completed'
        },
        project_id: {
            type: 'string',
            format: 'uuid',
            title: 'Project Id'
        },
        parent_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent Id'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        assignee_bot_user: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BotUserRef'
                },
                {
                    type: 'null'
                }
            ]
        },
        recurrence: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Recurrence'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'title',
        'id',
        'completed',
        'project_id'
    ],
    title: 'TaskPublic'
} as const;

export const TaskSortSchema = {
    type: 'string',
    enum: [
        'due_date',
        'priority'
    ],
    title: 'TaskSort'
} as const;

export const TaskUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        due_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Due Date'
        },
        priority: {
            anyOf: [
                {
                    $ref: '#/components/schemas/TaskPriority'
                },
                {
                    type: 'null'
                }
            ]
        },
        project_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Project Id'
        },
        assignee_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assignee Id'
        },
        completed: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        maxLength: 50,
                        minLength: 1
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        subtasks: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SubtaskCompletion'
                },
                {
                    type: 'null'
                }
            ]
        },
        recurrence: {
            anyOf: [
                {
                    $ref: '#/components/schemas/Recurrence'
                },
                {
                    type: 'null'
                }
            ]
        },
        due_date_scope: {
            anyOf: [
                {
                    $ref: '#/components/schemas/DueDateScope'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'TaskUpdate'
} as const;

export const TasksPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/TaskPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'TasksPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserRegister'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
