// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ActivityAction
 *
 * Everything the activity log records (FR-10.3).
 */
export type ActivityAction = 'task_created' | 'task_changed' | 'task_completed' | 'task_reopened' | 'task_deleted' | 'task_restored' | 'task_moved' | 'task_assigned' | 'task_unassigned' | 'project_created' | 'project_changed' | 'project_deleted' | 'project_restored' | 'comment_added' | 'comment_edited' | 'comment_deleted' | 'attachment_added' | 'attachment_deleted';

/**
 * ActivityEntityType
 */
export type ActivityEntityType = 'task' | 'project' | 'comment' | 'attachment';

/**
 * ActivityEntriesPublic
 */
export type ActivityEntriesPublic = {
    /**
     * Data
     */
    data: Array<ActivityEntryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ActivityEntryPublic
 */
export type ActivityEntryPublic = {
    /**
     * Id
     */
    id: string;
    action: ActivityAction;
    entity_type: ActivityEntityType;
    /**
     * Entity Id
     */
    entity_id: string;
    /**
     * Actor Id
     */
    actor_id: string;
    /**
     * Deletion Id
     */
    deletion_id?: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Entity Exists
     */
    entity_exists: boolean;
    /**
     * Entity Project Id
     */
    entity_project_id?: string | null;
    /**
     * Restorable
     */
    restorable?: boolean;
};

/**
 * AttachmentPublic
 */
export type AttachmentPublic = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Id
     */
    id: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * AttachmentsPublic
 */
export type AttachmentsPublic = {
    /**
     * Data
     */
    data: Array<AttachmentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_attachments-upload_attachment
 */
export type Body_attachments_upload_attachment = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * BotPermissions
 *
 * What a bot user may do inside the projects of its scope (FR-08.9,
 * FR-08.10).
 *
 * Only what can be granted is here. What a bot can never do — anything on
 * projects, editing or deleting comments — has no field to set to false:
 * the endpoints for it take a human caller, so a bot cannot reach them at
 * all. Tags have no field yet either, because what a tag permission would
 * mean is still an open question (Q-16); a bot changes no tags meanwhile.
 */
export type BotPermissions = {
    /**
     * Create Tasks
     */
    create_tasks?: boolean;
    /**
     * Read Tasks
     */
    read_tasks?: boolean;
    /**
     * Update Tasks
     */
    update_tasks?: boolean;
    /**
     * Delete Tasks
     */
    delete_tasks?: boolean;
    /**
     * Add Comments
     */
    add_comments?: boolean;
};

/**
 * BotScope
 *
 * Where a bot user may act and what it may do there.
 *
 * The projects are always named one by one: there is no value meaning "all
 * projects" (FR-08.6), so a project created tomorrow is never in the scope
 * of a bot set up today.
 */
export type BotScope = {
    /**
     * Project Ids
     */
    project_ids: Array<string>;
    permissions: BotPermissions;
};

/**
 * BotTokenIssued
 *
 * The one response that carries a bot user's token (FR-08.13).
 */
export type BotTokenIssued = {
    /**
     * Bot User Id
     */
    bot_user_id: string;
    /**
     * Token
     */
    token: string;
};

/**
 * BotUserCreate
 */
export type BotUserCreate = {
    /**
     * Name
     */
    name: string;
    scope: BotScope;
};

/**
 * BotUserPublic
 */
export type BotUserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    scope: BotScope;
    /**
     * Has Token
     */
    has_token: boolean;
    /**
     * Token Issued At
     */
    token_issued_at?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * BotUsersPublic
 */
export type BotUsersPublic = {
    /**
     * Data
     */
    data: Array<BotUserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Body
     */
    body: string;
};

/**
 * CommentPublic
 */
export type CommentPublic = {
    /**
     * Body
     */
    body: string;
    /**
     * Id
     */
    id: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CommentUpdate
 */
export type CommentUpdate = {
    /**
     * Body
     */
    body: string;
};

/**
 * CommentsPublic
 */
export type CommentsPublic = {
    /**
     * Data
     */
    data: Array<CommentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DueDateScope
 *
 * What moving the due date of an open recurring occurrence means for the rest
 * of its series.
 *
 * There is no default: a client that changes the date without saying which
 * one is refused, so a series is never rescheduled by omission (FR-01.17).
 */
export type DueDateScope = 'this_occurrence' | 'this_and_following';

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ProjectPublic
 */
export type ProjectPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Inbox
     */
    is_inbox: boolean;
    /**
     * Is Archived
     */
    is_archived: boolean;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ProjectsPublic
 */
export type ProjectsPublic = {
    /**
     * Data
     */
    data: Array<ProjectPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Recurrence
 *
 * How often a recurring task comes back: a fixed interval, never tied to when
 * an occurrence happened to be completed (FR-01.13, FR-01.15).
 */
export type Recurrence = {
    frequency: RecurrenceFrequency;
    /**
     * Interval Days
     */
    interval_days?: number | null;
};

/**
 * RecurrenceFrequency
 */
export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly' | 'every_n_days';

/**
 * SortOrder
 */
export type SortOrder = 'asc' | 'desc';

/**
 * SubtaskCompletion
 *
 * What a completion request says about the task's uncompleted subtasks.
 *
 * Sending neither value is not a default: the request is refused, so a client
 * never completes a parent without saying what happens below it (FR-02.6,
 * FR-02.7).
 */
export type SubtaskCompletion = 'leave_uncompleted' | 'complete';

/**
 * TagPublic
 */
export type TagPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
};

/**
 * TagsPublic
 */
export type TagsPublic = {
    /**
     * Data
     */
    data: Array<TagPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    priority?: TaskPriority | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
    recurrence?: Recurrence | null;
};

/**
 * TaskPriority
 */
export type TaskPriority = 'P1' | 'P2' | 'P3' | 'P4';

/**
 * TaskPublic
 */
export type TaskPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    priority?: TaskPriority | null;
    /**
     * Id
     */
    id: string;
    /**
     * Completed
     */
    completed: boolean;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
    recurrence?: Recurrence | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * TaskSort
 */
export type TaskSort = 'due_date' | 'priority';

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    priority?: TaskPriority | null;
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
    /**
     * Completed
     */
    completed?: boolean | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    subtasks?: SubtaskCompletion | null;
    recurrence?: Recurrence | null;
    due_date_scope?: DueDateScope | null;
};

/**
 * TasksPublic
 */
export type TasksPublic = {
    /**
     * Data
     */
    data: Array<TaskPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type projectsReadProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Archived
         */
        archived?: boolean;
    };
    url: '/api/v1/projects/';
};

export type projectsReadProjectsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsReadProjectsError = projectsReadProjectsErrors[keyof projectsReadProjectsErrors];

export type projectsReadProjectsResponses = {
    /**
     * Successful Response
     */
    200: ProjectsPublic;
};

export type projectsReadProjectsResponse = projectsReadProjectsResponses[keyof projectsReadProjectsResponses];

export type projectsCreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects/';
};

export type projectsCreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsCreateProjectError = projectsCreateProjectErrors[keyof projectsCreateProjectErrors];

export type projectsCreateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsCreateProjectResponse = projectsCreateProjectResponses[keyof projectsCreateProjectResponses];

export type projectsDeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type projectsDeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsDeleteProjectError = projectsDeleteProjectErrors[keyof projectsDeleteProjectErrors];

export type projectsDeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type projectsDeleteProjectResponse = projectsDeleteProjectResponses[keyof projectsDeleteProjectResponses];

export type projectsUpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type projectsUpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsUpdateProjectError = projectsUpdateProjectErrors[keyof projectsUpdateProjectErrors];

export type projectsUpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsUpdateProjectResponse = projectsUpdateProjectResponses[keyof projectsUpdateProjectResponses];

export type projectsArchiveProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/archive';
};

export type projectsArchiveProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsArchiveProjectError = projectsArchiveProjectErrors[keyof projectsArchiveProjectErrors];

export type projectsArchiveProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsArchiveProjectResponse = projectsArchiveProjectResponses[keyof projectsArchiveProjectResponses];

export type projectsUnarchiveProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/unarchive';
};

export type projectsUnarchiveProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsUnarchiveProjectError = projectsUnarchiveProjectErrors[keyof projectsUnarchiveProjectErrors];

export type projectsUnarchiveProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsUnarchiveProjectResponse = projectsUnarchiveProjectResponses[keyof projectsUnarchiveProjectResponses];

export type tasksReadTasksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Project Id
         */
        project_id?: string | null;
        /**
         * Assignee Id
         */
        assignee_id?: string | null;
        /**
         * Unassigned
         */
        unassigned?: boolean;
        /**
         * Tag
         */
        tag?: string | null;
        /**
         * Priority
         */
        priority?: TaskPriority | null;
        /**
         * Completed
         */
        completed?: boolean | null;
        /**
         * Due From
         */
        due_from?: string | null;
        /**
         * Due To
         */
        due_to?: string | null;
        /**
         * Overdue
         */
        overdue?: boolean;
        /**
         * Archived
         */
        archived?: boolean;
        /**
         * Sort
         */
        sort?: TaskSort | null;
        order?: SortOrder;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tasks/';
};

export type tasksReadTasksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksReadTasksError = tasksReadTasksErrors[keyof tasksReadTasksErrors];

export type tasksReadTasksResponses = {
    /**
     * Successful Response
     */
    200: TasksPublic;
};

export type tasksReadTasksResponse = tasksReadTasksResponses[keyof tasksReadTasksResponses];

export type tasksCreateTaskData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tasks/';
};

export type tasksCreateTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksCreateTaskError = tasksCreateTaskErrors[keyof tasksCreateTaskErrors];

export type tasksCreateTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksCreateTaskResponse = tasksCreateTaskResponses[keyof tasksCreateTaskResponses];

export type tasksDeleteTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Delete Subtasks
         */
        delete_subtasks?: boolean;
    };
    url: '/api/v1/tasks/{task_id}';
};

export type tasksDeleteTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksDeleteTaskError = tasksDeleteTaskErrors[keyof tasksDeleteTaskErrors];

export type tasksDeleteTaskResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type tasksDeleteTaskResponse = tasksDeleteTaskResponses[keyof tasksDeleteTaskResponses];

export type tasksReadTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type tasksReadTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksReadTaskError = tasksReadTaskErrors[keyof tasksReadTaskErrors];

export type tasksReadTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksReadTaskResponse = tasksReadTaskResponses[keyof tasksReadTaskResponses];

export type tasksUpdateTaskData = {
    body: TaskUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type tasksUpdateTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksUpdateTaskError = tasksUpdateTaskErrors[keyof tasksUpdateTaskErrors];

export type tasksUpdateTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksUpdateTaskResponse = tasksUpdateTaskResponses[keyof tasksUpdateTaskResponses];

export type commentsReadCommentsData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/comments/';
};

export type commentsReadCommentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsReadCommentsError = commentsReadCommentsErrors[keyof commentsReadCommentsErrors];

export type commentsReadCommentsResponses = {
    /**
     * Successful Response
     */
    200: CommentsPublic;
};

export type commentsReadCommentsResponse = commentsReadCommentsResponses[keyof commentsReadCommentsResponses];

export type commentsCreateCommentData = {
    body: CommentCreate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/comments/';
};

export type commentsCreateCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsCreateCommentError = commentsCreateCommentErrors[keyof commentsCreateCommentErrors];

export type commentsCreateCommentResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type commentsCreateCommentResponse = commentsCreateCommentResponses[keyof commentsCreateCommentResponses];

export type commentsDeleteCommentData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}';
};

export type commentsDeleteCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsDeleteCommentError = commentsDeleteCommentErrors[keyof commentsDeleteCommentErrors];

export type commentsDeleteCommentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type commentsDeleteCommentResponse = commentsDeleteCommentResponses[keyof commentsDeleteCommentResponses];

export type commentsUpdateCommentData = {
    body: CommentUpdate;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}';
};

export type commentsUpdateCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsUpdateCommentError = commentsUpdateCommentErrors[keyof commentsUpdateCommentErrors];

export type commentsUpdateCommentResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type commentsUpdateCommentResponse = commentsUpdateCommentResponses[keyof commentsUpdateCommentResponses];

export type attachmentsReadAttachmentsData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/attachments/';
};

export type attachmentsReadAttachmentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsReadAttachmentsError = attachmentsReadAttachmentsErrors[keyof attachmentsReadAttachmentsErrors];

export type attachmentsReadAttachmentsResponses = {
    /**
     * Successful Response
     */
    200: AttachmentsPublic;
};

export type attachmentsReadAttachmentsResponse = attachmentsReadAttachmentsResponses[keyof attachmentsReadAttachmentsResponses];

export type attachmentsUploadAttachmentData = {
    body: Body_attachments_upload_attachment;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/attachments/';
};

export type attachmentsUploadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsUploadAttachmentError = attachmentsUploadAttachmentErrors[keyof attachmentsUploadAttachmentErrors];

export type attachmentsUploadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: AttachmentPublic;
};

export type attachmentsUploadAttachmentResponse = attachmentsUploadAttachmentResponses[keyof attachmentsUploadAttachmentResponses];

export type attachmentsDeleteAttachmentData = {
    body?: never;
    path: {
        /**
         * Attachment Id
         */
        attachment_id: string;
    };
    query?: never;
    url: '/api/v1/attachments/{attachment_id}';
};

export type attachmentsDeleteAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsDeleteAttachmentError = attachmentsDeleteAttachmentErrors[keyof attachmentsDeleteAttachmentErrors];

export type attachmentsDeleteAttachmentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type attachmentsDeleteAttachmentResponse = attachmentsDeleteAttachmentResponses[keyof attachmentsDeleteAttachmentResponses];

export type attachmentsDownloadAttachmentData = {
    body?: never;
    path: {
        /**
         * Attachment Id
         */
        attachment_id: string;
    };
    query?: never;
    url: '/api/v1/attachments/{attachment_id}';
};

export type attachmentsDownloadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsDownloadAttachmentError = attachmentsDownloadAttachmentErrors[keyof attachmentsDownloadAttachmentErrors];

export type attachmentsDownloadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type tagsReadTagsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tags/';
};

export type tagsReadTagsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsReadTagsError = tagsReadTagsErrors[keyof tagsReadTagsErrors];

export type tagsReadTagsResponses = {
    /**
     * Successful Response
     */
    200: TagsPublic;
};

export type tagsReadTagsResponse = tagsReadTagsResponses[keyof tagsReadTagsResponses];

export type activityReadActivityLogData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/activity-log/';
};

export type activityReadActivityLogErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type activityReadActivityLogError = activityReadActivityLogErrors[keyof activityReadActivityLogErrors];

export type activityReadActivityLogResponses = {
    /**
     * Successful Response
     */
    200: ActivityEntriesPublic;
};

export type activityReadActivityLogResponse = activityReadActivityLogResponses[keyof activityReadActivityLogResponses];

export type activityRestoreFromActivityEntryData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/activity-log/{entry_id}/restore';
};

export type activityRestoreFromActivityEntryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type activityRestoreFromActivityEntryError = activityRestoreFromActivityEntryErrors[keyof activityRestoreFromActivityEntryErrors];

export type activityRestoreFromActivityEntryResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type activityRestoreFromActivityEntryResponse = activityRestoreFromActivityEntryResponses[keyof activityRestoreFromActivityEntryResponses];

export type botsReadBotUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/bot-users/';
};

export type botsReadBotUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsReadBotUsersError = botsReadBotUsersErrors[keyof botsReadBotUsersErrors];

export type botsReadBotUsersResponses = {
    /**
     * Successful Response
     */
    200: BotUsersPublic;
};

export type botsReadBotUsersResponse = botsReadBotUsersResponses[keyof botsReadBotUsersResponses];

export type botsCreateBotUserData = {
    body: BotUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/bot-users/';
};

export type botsCreateBotUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsCreateBotUserError = botsCreateBotUserErrors[keyof botsCreateBotUserErrors];

export type botsCreateBotUserResponses = {
    /**
     * Successful Response
     */
    200: BotUserPublic;
};

export type botsCreateBotUserResponse = botsCreateBotUserResponses[keyof botsCreateBotUserResponses];

export type botsIssueBotUserTokenData = {
    body?: never;
    path: {
        /**
         * Bot User Id
         */
        bot_user_id: string;
    };
    query?: never;
    url: '/api/v1/bot-users/{bot_user_id}/token';
};

export type botsIssueBotUserTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsIssueBotUserTokenError = botsIssueBotUserTokenErrors[keyof botsIssueBotUserTokenErrors];

export type botsIssueBotUserTokenResponses = {
    /**
     * Successful Response
     */
    200: BotTokenIssued;
};

export type botsIssueBotUserTokenResponse = botsIssueBotUserTokenResponses[keyof botsIssueBotUserTokenResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
