// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ActivityAction
 *
 * Everything the activity log records (FR-10.3).
 */
export type ActivityAction = 'task_created' | 'task_changed' | 'tasks_bulk_changed' | 'task_completed' | 'task_reopened' | 'task_status_changed' | 'task_deleted' | 'task_restored' | 'task_moved' | 'task_assigned' | 'task_unassigned' | 'project_created' | 'project_changed' | 'project_deleted' | 'project_restored' | 'comment_added' | 'comment_edited' | 'comment_deleted' | 'attachment_added' | 'attachment_deleted' | 'tag_created' | 'tag_renamed' | 'tag_deleted' | 'tag_merged';

/**
 * ActivityEntityType
 */
export type ActivityEntityType = 'task' | 'project' | 'comment' | 'attachment' | 'tag';

/**
 * ActivityEntriesPublic
 */
export type ActivityEntriesPublic = {
    /**
     * Data
     */
    data: Array<ActivityEntryPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ActivityEntryPublic
 */
export type ActivityEntryPublic = {
    /**
     * Id
     */
    id: string;
    action: ActivityAction;
    entity_type: ActivityEntityType;
    /**
     * Entity Id
     */
    entity_id: string;
    /**
     * Actor Id
     */
    actor_id?: string | null;
    /**
     * Actor Bot User Id
     */
    actor_bot_user_id?: string | null;
    /**
     * Actor Bot User Name
     */
    actor_bot_user_name?: string | null;
    /**
     * Deletion Id
     */
    deletion_id?: string | null;
    /**
     * Details
     */
    details: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Entity Exists
     */
    entity_exists: boolean;
    /**
     * Entity Project Id
     */
    entity_project_id?: string | null;
    /**
     * Restorable
     */
    restorable?: boolean;
};

/**
 * ActivityKind
 *
 * How a reader groups the log's actions in order to narrow it.
 *
 * Coarser than `ActivityAction` on purpose: someone asks the log what they
 * finished, filed or threw away — not which of two dozen action names an
 * entry happens to carry. The groups do not overlap, so an entry answers to
 * exactly one of them and a reader never meets the same change twice.
 *
 * The grouping is the server's rather than a set of actions the client
 * sends, because `COMPLETED` is not a set of actions at all: closing tasks
 * in a batch writes one `TASKS_BULK_CHANGED` entry naming the new status,
 * not a completion per task, so the group has to read that entry's details.
 */
export type ActivityKind = 'completed' | 'created' | 'changed' | 'deleted' | 'comments' | 'tags';

/**
 * AttachmentPublic
 */
export type AttachmentPublic = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Size
     */
    size: number;
    /**
     * Id
     */
    id: string;
    /**
     * Task Id
     */
    task_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * AttachmentsPublic
 */
export type AttachmentsPublic = {
    /**
     * Data
     */
    data: Array<AttachmentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_attachments-upload_attachment
 */
export type Body_attachments_upload_attachment = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * BotPermissions
 *
 * What a bot user may do inside the projects of its scope (FR-08.9,
 * FR-08.10).
 *
 * Only what can be granted is here. What a bot can never do — anything on
 * projects, editing or deleting comments, renaming or deleting tags — has no
 * field to set to false: the endpoints for it take a human caller, so a bot
 * cannot reach them at all. Reading tags needs no field either: every bot
 * user reads its owner's whole tag vocabulary, whatever its scope
 * (ADR-0003).
 */
export type BotPermissions = {
    /**
     * Create Tasks
     */
    create_tasks?: boolean;
    /**
     * Read Tasks
     */
    read_tasks?: boolean;
    /**
     * Update Tasks
     */
    update_tasks?: boolean;
    /**
     * Delete Tasks
     */
    delete_tasks?: boolean;
    /**
     * Add Comments
     */
    add_comments?: boolean;
    /**
     * Create Tags
     */
    create_tags?: boolean;
};

/**
 * BotScope
 *
 * Where a bot user may act and what it may do there.
 *
 * The projects are always named one by one: there is no value meaning "all
 * projects" (FR-08.6), so a project created tomorrow is never in the scope
 * of a bot set up today.
 */
export type BotScope = {
    /**
     * Project Ids
     */
    project_ids: Array<string>;
    permissions: BotPermissions;
};

/**
 * BotTokenIssue
 *
 * How a token is issued: with an expiry, or none to last until revoked.
 */
export type BotTokenIssue = {
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * BotTokenIssued
 *
 * The one response that carries a bot user's token (FR-08.13).
 */
export type BotTokenIssued = {
    /**
     * Bot User Id
     */
    bot_user_id: string;
    /**
     * Token
     */
    token: string;
    /**
     * Expires At
     */
    expires_at?: string | null;
};

/**
 * BotUserCreate
 */
export type BotUserCreate = {
    /**
     * Name
     */
    name: string;
    scope: BotScope;
};

/**
 * BotUserPublic
 */
export type BotUserPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    scope: BotScope;
    /**
     * Deleted
     */
    deleted?: boolean;
    /**
     * Has Token
     */
    has_token: boolean;
    /**
     * Token Issued At
     */
    token_issued_at?: string | null;
    /**
     * Token Expires At
     */
    token_expires_at?: string | null;
    /**
     * Token Last Used At
     */
    token_last_used_at?: string | null;
    /**
     * Token Revoked At
     */
    token_revoked_at?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * BotUserRef
 *
 * A bot user as a task or comment names it: the one it is assigned to, or
 * the one that wrote it. A deleted bot user stays on what it was given and
 * what it wrote (FR-08.19, FR-08.21), marked deleted.
 */
export type BotUserRef = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Deleted
     */
    deleted: boolean;
};

/**
 * BotUserUpdate
 *
 * A change to a bot user: its name, its scope, or both. A scope is sent
 * whole — its projects and its permissions — and replaces the one the bot
 * user had, so what is granted is always exactly what the user last saw.
 */
export type BotUserUpdate = {
    /**
     * Name
     */
    name?: string | null;
    scope?: BotScope | null;
};

/**
 * BotUsersPublic
 */
export type BotUsersPublic = {
    /**
     * Data
     */
    data: Array<BotUserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * BulkResult
 *
 * How many tasks one act changed.
 */
export type BulkResult = {
    /**
     * Updated
     */
    updated?: number;
    /**
     * Deleted
     */
    deleted?: number;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
    /**
     * Body
     */
    body: string;
};

/**
 * CommentPublic
 */
export type CommentPublic = {
    /**
     * Body
     */
    body: string;
    /**
     * Id
     */
    id: string;
    /**
     * Task Id
     */
    task_id: string;
    author_bot_user?: BotUserRef | null;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * CommentUpdate
 */
export type CommentUpdate = {
    /**
     * Body
     */
    body: string;
};

/**
 * CommentsPublic
 */
export type CommentsPublic = {
    /**
     * Data
     */
    data: Array<CommentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * DueDateScope
 *
 * What moving the due date of an open recurring occurrence means for the rest
 * of its series.
 *
 * There is no default: a client that changes the date without saying which
 * one is refused, so a series is never rescheduled by omission (FR-01.17).
 */
export type DueDateScope = 'this_occurrence' | 'this_and_following';

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ProjectPublic
 */
export type ProjectPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Inbox
     */
    is_inbox: boolean;
    /**
     * Is Archived
     */
    is_archived: boolean;
    /**
     * Task Count
     */
    task_count?: number;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
};

/**
 * ProjectsPublic
 */
export type ProjectsPublic = {
    /**
     * Data
     */
    data: Array<ProjectPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Recurrence
 *
 * How often a recurring task comes back: a fixed interval, never tied to when
 * an occurrence happened to be done (FR-01.13, FR-01.15).
 */
export type Recurrence = {
    frequency: RecurrenceFrequency;
    /**
     * Interval Days
     */
    interval_days?: number | null;
};

/**
 * RecurrenceFrequency
 */
export type RecurrenceFrequency = 'daily' | 'weekly' | 'monthly' | 'every_n_days';

/**
 * SortOrder
 */
export type SortOrder = 'asc' | 'desc';

/**
 * SubtaskCompletion
 *
 * What a request that moves a task to done says about its open subtasks.
 *
 * Sending neither value is not a default: the request is refused, so a client
 * never closes a parent without saying what happens below it (FR-02.6,
 * FR-02.7). `complete` moves the subtasks to done; `leave_uncompleted` leaves
 * each in the open status it has.
 */
export type SubtaskCompletion = 'leave_uncompleted' | 'complete';

/**
 * TagCreate
 */
export type TagCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * TagDuplicateDismiss
 *
 * Every member of the group to stop offering, and nothing else.
 */
export type TagDuplicateDismiss = {
    /**
     * Tag Ids
     */
    tag_ids: Array<string>;
};

/**
 * TagDuplicateGroup
 *
 * Tags whose names differ only in form: a suggestion to merge them.
 */
export type TagDuplicateGroup = {
    /**
     * Tags
     */
    tags: Array<TagPublic>;
};

/**
 * TagDuplicateGroups
 */
export type TagDuplicateGroups = {
    /**
     * Data
     */
    data: Array<TagDuplicateGroup>;
};

/**
 * TagMerge
 *
 * The tags to fold into the one the merge is addressed to.
 */
export type TagMerge = {
    /**
     * Source Ids
     */
    source_ids: Array<string>;
};

/**
 * TagMergePreview
 *
 * What a merge would move: the tasks carrying any of the sources, each
 * counted once, live and archived apart (FR-01.27).
 */
export type TagMergePreview = {
    /**
     * Task Count
     */
    task_count: number;
    /**
     * Archived Task Count
     */
    archived_task_count: number;
};

/**
 * TagPublic
 */
export type TagPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Task Count
     */
    task_count?: number;
    /**
     * Archived Task Count
     */
    archived_task_count?: number;
    created_by_bot_user?: BotUserRef | null;
};

/**
 * TagUpdate
 */
export type TagUpdate = {
    /**
     * Name
     */
    name: string;
};

/**
 * TagsPublic
 */
export type TagsPublic = {
    /**
     * Data
     */
    data: Array<TagPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * TaskBulkDelete
 *
 * One deletion event over several tasks, restorable as the one act it was.
 */
export type TaskBulkDelete = {
    /**
     * Task Ids
     */
    task_ids: Array<string>;
    /**
     * Delete Subtasks
     */
    delete_subtasks?: boolean;
};

/**
 * TaskBulkUpdate
 *
 * One set of changes for many tasks: the single-task update, plus the tasks
 * it applies to.
 *
 * `add_tags` and `remove_tags` rather than `tags`: a batch adds a label to a
 * selection or takes one off it, and replacing every task's tags wholesale
 * would destroy what each of them already carried.
 */
export type TaskBulkUpdate = {
    /**
     * Task Ids
     */
    task_ids: Array<string>;
    status?: TaskStatus | null;
    subtasks?: SubtaskCompletion | null;
    priority?: TaskPriority | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
    /**
     * Add Tags
     */
    add_tags?: Array<string>;
    /**
     * Remove Tags
     */
    remove_tags?: Array<string>;
};

/**
 * TaskCreate
 */
export type TaskCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    priority?: TaskPriority | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
    recurrence?: Recurrence | null;
    status?: TaskStatus;
};

/**
 * TaskPriority
 */
export type TaskPriority = 'P1' | 'P2' | 'P3' | 'P4';

/**
 * TaskPublic
 */
export type TaskPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    priority?: TaskPriority | null;
    /**
     * Id
     */
    id: string;
    status: TaskStatus;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Parent Id
     */
    parent_id?: string | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
    assignee_bot_user?: BotUserRef | null;
    /**
     * Reporter Id
     */
    reporter_id?: string | null;
    reporter_bot_user?: BotUserRef | null;
    recurrence?: Recurrence | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Subtask Count
     */
    subtask_count?: number;
    /**
     * Subtasks Done
     */
    subtasks_done?: number;
};

/**
 * TaskSort
 *
 * How a task list can be ordered, and which way round each one naturally
 * runs when the request names no direction (FR-06.4).
 *
 * Due date means soonest first and priority means P1 first, because that is
 * the work to reach for. Creation means newest first, because the reason to
 * order by it is to see what has just arrived.
 */
export type TaskSort = 'due_date' | 'priority' | 'created_at';

/**
 * TaskStatus
 *
 * Where a task stands (FR-01.4). Four fixed values rather than user-defined
 * ones (ADR-0004): every rule in the product only needs to know whether a
 * task is open or done, and the three open values tell apart who holds the
 * next move.
 */
export type TaskStatus = 'todo' | 'in_progress' | 'waiting' | 'done';

/**
 * TaskUpdate
 */
export type TaskUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    priority?: TaskPriority | null;
    /**
     * Project Id
     */
    project_id?: string | null;
    /**
     * Assignee Id
     */
    assignee_id?: string | null;
    status?: TaskStatus | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
    subtasks?: SubtaskCompletion | null;
    recurrence?: Recurrence | null;
    due_date_scope?: DueDateScope | null;
};

/**
 * TasksPublic
 */
export type TasksPublic = {
    /**
     * Data
     */
    data: Array<TaskPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type projectsReadProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Archived
         */
        archived?: boolean;
    };
    url: '/api/v1/projects/';
};

export type projectsReadProjectsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsReadProjectsError = projectsReadProjectsErrors[keyof projectsReadProjectsErrors];

export type projectsReadProjectsResponses = {
    /**
     * Successful Response
     */
    200: ProjectsPublic;
};

export type projectsReadProjectsResponse = projectsReadProjectsResponses[keyof projectsReadProjectsResponses];

export type projectsCreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects/';
};

export type projectsCreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsCreateProjectError = projectsCreateProjectErrors[keyof projectsCreateProjectErrors];

export type projectsCreateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsCreateProjectResponse = projectsCreateProjectResponses[keyof projectsCreateProjectResponses];

export type projectsDeleteProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type projectsDeleteProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsDeleteProjectError = projectsDeleteProjectErrors[keyof projectsDeleteProjectErrors];

export type projectsDeleteProjectResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type projectsDeleteProjectResponse = projectsDeleteProjectResponses[keyof projectsDeleteProjectResponses];

export type projectsReadProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type projectsReadProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsReadProjectError = projectsReadProjectErrors[keyof projectsReadProjectErrors];

export type projectsReadProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsReadProjectResponse = projectsReadProjectResponses[keyof projectsReadProjectResponses];

export type projectsUpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type projectsUpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsUpdateProjectError = projectsUpdateProjectErrors[keyof projectsUpdateProjectErrors];

export type projectsUpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsUpdateProjectResponse = projectsUpdateProjectResponses[keyof projectsUpdateProjectResponses];

export type projectsArchiveProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/archive';
};

export type projectsArchiveProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsArchiveProjectError = projectsArchiveProjectErrors[keyof projectsArchiveProjectErrors];

export type projectsArchiveProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsArchiveProjectResponse = projectsArchiveProjectResponses[keyof projectsArchiveProjectResponses];

export type projectsUnarchiveProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/unarchive';
};

export type projectsUnarchiveProjectErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type projectsUnarchiveProjectError = projectsUnarchiveProjectErrors[keyof projectsUnarchiveProjectErrors];

export type projectsUnarchiveProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectPublic;
};

export type projectsUnarchiveProjectResponse = projectsUnarchiveProjectResponses[keyof projectsUnarchiveProjectResponses];

export type tasksReadTasksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Project Id
         */
        project_id?: string | null;
        /**
         * Parent Id
         */
        parent_id?: string | null;
        /**
         * Assignee Id
         */
        assignee_id?: string | null;
        /**
         * Unassigned
         */
        unassigned?: boolean;
        /**
         * Tag
         */
        tag?: string | null;
        /**
         * Priority
         */
        priority?: TaskPriority | null;
        /**
         * Status
         */
        status?: Array<TaskStatus> | null;
        /**
         * Due From
         */
        due_from?: string | null;
        /**
         * Due To
         */
        due_to?: string | null;
        /**
         * Overdue
         */
        overdue?: boolean;
        /**
         * Archived
         */
        archived?: boolean;
        /**
         * Sort
         */
        sort?: TaskSort | null;
        /**
         * Order
         */
        order?: SortOrder | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tasks/';
};

export type tasksReadTasksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksReadTasksError = tasksReadTasksErrors[keyof tasksReadTasksErrors];

export type tasksReadTasksResponses = {
    /**
     * Successful Response
     */
    200: TasksPublic;
};

export type tasksReadTasksResponse = tasksReadTasksResponses[keyof tasksReadTasksResponses];

export type tasksCreateTaskData = {
    body: TaskCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tasks/';
};

export type tasksCreateTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksCreateTaskError = tasksCreateTaskErrors[keyof tasksCreateTaskErrors];

export type tasksCreateTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksCreateTaskResponse = tasksCreateTaskResponses[keyof tasksCreateTaskResponses];

export type tasksBulkUpdateTasksData = {
    body: TaskBulkUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/tasks/bulk';
};

export type tasksBulkUpdateTasksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksBulkUpdateTasksError = tasksBulkUpdateTasksErrors[keyof tasksBulkUpdateTasksErrors];

export type tasksBulkUpdateTasksResponses = {
    /**
     * Successful Response
     */
    200: BulkResult;
};

export type tasksBulkUpdateTasksResponse = tasksBulkUpdateTasksResponses[keyof tasksBulkUpdateTasksResponses];

export type tasksBulkDeleteTasksData = {
    body: TaskBulkDelete;
    path?: never;
    query?: never;
    url: '/api/v1/tasks/bulk-delete';
};

export type tasksBulkDeleteTasksErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksBulkDeleteTasksError = tasksBulkDeleteTasksErrors[keyof tasksBulkDeleteTasksErrors];

export type tasksBulkDeleteTasksResponses = {
    /**
     * Successful Response
     */
    200: BulkResult;
};

export type tasksBulkDeleteTasksResponse = tasksBulkDeleteTasksResponses[keyof tasksBulkDeleteTasksResponses];

export type tasksDeleteTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: {
        /**
         * Delete Subtasks
         */
        delete_subtasks?: boolean;
    };
    url: '/api/v1/tasks/{task_id}';
};

export type tasksDeleteTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksDeleteTaskError = tasksDeleteTaskErrors[keyof tasksDeleteTaskErrors];

export type tasksDeleteTaskResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type tasksDeleteTaskResponse = tasksDeleteTaskResponses[keyof tasksDeleteTaskResponses];

export type tasksReadTaskData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type tasksReadTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksReadTaskError = tasksReadTaskErrors[keyof tasksReadTaskErrors];

export type tasksReadTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksReadTaskResponse = tasksReadTaskResponses[keyof tasksReadTaskResponses];

export type tasksUpdateTaskData = {
    body: TaskUpdate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}';
};

export type tasksUpdateTaskErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tasksUpdateTaskError = tasksUpdateTaskErrors[keyof tasksUpdateTaskErrors];

export type tasksUpdateTaskResponses = {
    /**
     * Successful Response
     */
    200: TaskPublic;
};

export type tasksUpdateTaskResponse = tasksUpdateTaskResponses[keyof tasksUpdateTaskResponses];

export type commentsReadCommentsData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/comments/';
};

export type commentsReadCommentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsReadCommentsError = commentsReadCommentsErrors[keyof commentsReadCommentsErrors];

export type commentsReadCommentsResponses = {
    /**
     * Successful Response
     */
    200: CommentsPublic;
};

export type commentsReadCommentsResponse = commentsReadCommentsResponses[keyof commentsReadCommentsResponses];

export type commentsCreateCommentData = {
    body: CommentCreate;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/comments/';
};

export type commentsCreateCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsCreateCommentError = commentsCreateCommentErrors[keyof commentsCreateCommentErrors];

export type commentsCreateCommentResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type commentsCreateCommentResponse = commentsCreateCommentResponses[keyof commentsCreateCommentResponses];

export type commentsDeleteCommentData = {
    body?: never;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}';
};

export type commentsDeleteCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsDeleteCommentError = commentsDeleteCommentErrors[keyof commentsDeleteCommentErrors];

export type commentsDeleteCommentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type commentsDeleteCommentResponse = commentsDeleteCommentResponses[keyof commentsDeleteCommentResponses];

export type commentsUpdateCommentData = {
    body: CommentUpdate;
    path: {
        /**
         * Comment Id
         */
        comment_id: string;
    };
    query?: never;
    url: '/api/v1/comments/{comment_id}';
};

export type commentsUpdateCommentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type commentsUpdateCommentError = commentsUpdateCommentErrors[keyof commentsUpdateCommentErrors];

export type commentsUpdateCommentResponses = {
    /**
     * Successful Response
     */
    200: CommentPublic;
};

export type commentsUpdateCommentResponse = commentsUpdateCommentResponses[keyof commentsUpdateCommentResponses];

export type attachmentsReadAttachmentsData = {
    body?: never;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/attachments/';
};

export type attachmentsReadAttachmentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsReadAttachmentsError = attachmentsReadAttachmentsErrors[keyof attachmentsReadAttachmentsErrors];

export type attachmentsReadAttachmentsResponses = {
    /**
     * Successful Response
     */
    200: AttachmentsPublic;
};

export type attachmentsReadAttachmentsResponse = attachmentsReadAttachmentsResponses[keyof attachmentsReadAttachmentsResponses];

export type attachmentsUploadAttachmentData = {
    body: Body_attachments_upload_attachment;
    path: {
        /**
         * Task Id
         */
        task_id: string;
    };
    query?: never;
    url: '/api/v1/tasks/{task_id}/attachments/';
};

export type attachmentsUploadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsUploadAttachmentError = attachmentsUploadAttachmentErrors[keyof attachmentsUploadAttachmentErrors];

export type attachmentsUploadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: AttachmentPublic;
};

export type attachmentsUploadAttachmentResponse = attachmentsUploadAttachmentResponses[keyof attachmentsUploadAttachmentResponses];

export type attachmentsDeleteAttachmentData = {
    body?: never;
    path: {
        /**
         * Attachment Id
         */
        attachment_id: string;
    };
    query?: never;
    url: '/api/v1/attachments/{attachment_id}';
};

export type attachmentsDeleteAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsDeleteAttachmentError = attachmentsDeleteAttachmentErrors[keyof attachmentsDeleteAttachmentErrors];

export type attachmentsDeleteAttachmentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type attachmentsDeleteAttachmentResponse = attachmentsDeleteAttachmentResponses[keyof attachmentsDeleteAttachmentResponses];

export type attachmentsDownloadAttachmentData = {
    body?: never;
    path: {
        /**
         * Attachment Id
         */
        attachment_id: string;
    };
    query?: never;
    url: '/api/v1/attachments/{attachment_id}';
};

export type attachmentsDownloadAttachmentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type attachmentsDownloadAttachmentError = attachmentsDownloadAttachmentErrors[keyof attachmentsDownloadAttachmentErrors];

export type attachmentsDownloadAttachmentResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type tagsReadTagsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Q
         */
        q?: string | null;
        /**
         * Near
         */
        near?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/tags/';
};

export type tagsReadTagsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsReadTagsError = tagsReadTagsErrors[keyof tagsReadTagsErrors];

export type tagsReadTagsResponses = {
    /**
     * Successful Response
     */
    200: TagsPublic;
};

export type tagsReadTagsResponse = tagsReadTagsResponses[keyof tagsReadTagsResponses];

export type tagsCreateTagData = {
    body: TagCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tags/';
};

export type tagsCreateTagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsCreateTagError = tagsCreateTagErrors[keyof tagsCreateTagErrors];

export type tagsCreateTagResponses = {
    /**
     * Successful Response
     */
    200: TagPublic;
};

export type tagsCreateTagResponse = tagsCreateTagResponses[keyof tagsCreateTagResponses];

export type tagsReadTagDuplicatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tags/duplicates';
};

export type tagsReadTagDuplicatesResponses = {
    /**
     * Successful Response
     */
    200: TagDuplicateGroups;
};

export type tagsReadTagDuplicatesResponse = tagsReadTagDuplicatesResponses[keyof tagsReadTagDuplicatesResponses];

export type tagsDismissTagDuplicatesData = {
    body: TagDuplicateDismiss;
    path?: never;
    query?: never;
    url: '/api/v1/tags/duplicates/dismiss';
};

export type tagsDismissTagDuplicatesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsDismissTagDuplicatesError = tagsDismissTagDuplicatesErrors[keyof tagsDismissTagDuplicatesErrors];

export type tagsDismissTagDuplicatesResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type tagsDismissTagDuplicatesResponse = tagsDismissTagDuplicatesResponses[keyof tagsDismissTagDuplicatesResponses];

export type tagsDeleteTagData = {
    body?: never;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/v1/tags/{tag_id}';
};

export type tagsDeleteTagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsDeleteTagError = tagsDeleteTagErrors[keyof tagsDeleteTagErrors];

export type tagsDeleteTagResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type tagsDeleteTagResponse = tagsDeleteTagResponses[keyof tagsDeleteTagResponses];

export type tagsReadTagData = {
    body?: never;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/v1/tags/{tag_id}';
};

export type tagsReadTagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsReadTagError = tagsReadTagErrors[keyof tagsReadTagErrors];

export type tagsReadTagResponses = {
    /**
     * Successful Response
     */
    200: TagPublic;
};

export type tagsReadTagResponse = tagsReadTagResponses[keyof tagsReadTagResponses];

export type tagsRenameTagData = {
    body: TagUpdate;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/v1/tags/{tag_id}';
};

export type tagsRenameTagErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsRenameTagError = tagsRenameTagErrors[keyof tagsRenameTagErrors];

export type tagsRenameTagResponses = {
    /**
     * Successful Response
     */
    200: TagPublic;
};

export type tagsRenameTagResponse = tagsRenameTagResponses[keyof tagsRenameTagResponses];

export type tagsPreviewTagMergeData = {
    body?: never;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query: {
        /**
         * Source Ids
         */
        source_ids: Array<string>;
    };
    url: '/api/v1/tags/{tag_id}/merge-preview';
};

export type tagsPreviewTagMergeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsPreviewTagMergeError = tagsPreviewTagMergeErrors[keyof tagsPreviewTagMergeErrors];

export type tagsPreviewTagMergeResponses = {
    /**
     * Successful Response
     */
    200: TagMergePreview;
};

export type tagsPreviewTagMergeResponse = tagsPreviewTagMergeResponses[keyof tagsPreviewTagMergeResponses];

export type tagsMergeTagsData = {
    body: TagMerge;
    path: {
        /**
         * Tag Id
         */
        tag_id: string;
    };
    query?: never;
    url: '/api/v1/tags/{tag_id}/merge';
};

export type tagsMergeTagsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type tagsMergeTagsError = tagsMergeTagsErrors[keyof tagsMergeTagsErrors];

export type tagsMergeTagsResponses = {
    /**
     * Successful Response
     */
    200: TagPublic;
};

export type tagsMergeTagsResponse = tagsMergeTagsResponses[keyof tagsMergeTagsResponses];

export type activityReadActivityLogData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Actor Bot User Id
         */
        actor_bot_user_id?: string | null;
        /**
         * Kind
         */
        kind?: ActivityKind | null;
    };
    url: '/api/v1/activity-log/';
};

export type activityReadActivityLogErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type activityReadActivityLogError = activityReadActivityLogErrors[keyof activityReadActivityLogErrors];

export type activityReadActivityLogResponses = {
    /**
     * Successful Response
     */
    200: ActivityEntriesPublic;
};

export type activityReadActivityLogResponse = activityReadActivityLogResponses[keyof activityReadActivityLogResponses];

export type activityRestoreFromActivityEntryData = {
    body?: never;
    path: {
        /**
         * Entry Id
         */
        entry_id: string;
    };
    query?: never;
    url: '/api/v1/activity-log/{entry_id}/restore';
};

export type activityRestoreFromActivityEntryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type activityRestoreFromActivityEntryError = activityRestoreFromActivityEntryErrors[keyof activityRestoreFromActivityEntryErrors];

export type activityRestoreFromActivityEntryResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type activityRestoreFromActivityEntryResponse = activityRestoreFromActivityEntryResponses[keyof activityRestoreFromActivityEntryResponses];

export type botsReadBotUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/bot-users/';
};

export type botsReadBotUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsReadBotUsersError = botsReadBotUsersErrors[keyof botsReadBotUsersErrors];

export type botsReadBotUsersResponses = {
    /**
     * Successful Response
     */
    200: BotUsersPublic;
};

export type botsReadBotUsersResponse = botsReadBotUsersResponses[keyof botsReadBotUsersResponses];

export type botsCreateBotUserData = {
    body: BotUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/bot-users/';
};

export type botsCreateBotUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsCreateBotUserError = botsCreateBotUserErrors[keyof botsCreateBotUserErrors];

export type botsCreateBotUserResponses = {
    /**
     * Successful Response
     */
    200: BotUserPublic;
};

export type botsCreateBotUserResponse = botsCreateBotUserResponses[keyof botsCreateBotUserResponses];

export type botsDeleteBotUserData = {
    body?: never;
    path: {
        /**
         * Bot User Id
         */
        bot_user_id: string;
    };
    query?: never;
    url: '/api/v1/bot-users/{bot_user_id}';
};

export type botsDeleteBotUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsDeleteBotUserError = botsDeleteBotUserErrors[keyof botsDeleteBotUserErrors];

export type botsDeleteBotUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type botsDeleteBotUserResponse = botsDeleteBotUserResponses[keyof botsDeleteBotUserResponses];

export type botsReadBotUserData = {
    body?: never;
    path: {
        /**
         * Bot User Id
         */
        bot_user_id: string;
    };
    query?: never;
    url: '/api/v1/bot-users/{bot_user_id}';
};

export type botsReadBotUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsReadBotUserError = botsReadBotUserErrors[keyof botsReadBotUserErrors];

export type botsReadBotUserResponses = {
    /**
     * Successful Response
     */
    200: BotUserPublic;
};

export type botsReadBotUserResponse = botsReadBotUserResponses[keyof botsReadBotUserResponses];

export type botsUpdateBotUserData = {
    body: BotUserUpdate;
    path: {
        /**
         * Bot User Id
         */
        bot_user_id: string;
    };
    query?: never;
    url: '/api/v1/bot-users/{bot_user_id}';
};

export type botsUpdateBotUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsUpdateBotUserError = botsUpdateBotUserErrors[keyof botsUpdateBotUserErrors];

export type botsUpdateBotUserResponses = {
    /**
     * Successful Response
     */
    200: BotUserPublic;
};

export type botsUpdateBotUserResponse = botsUpdateBotUserResponses[keyof botsUpdateBotUserResponses];

export type botsRevokeBotUserTokenData = {
    body?: never;
    path: {
        /**
         * Bot User Id
         */
        bot_user_id: string;
    };
    query?: never;
    url: '/api/v1/bot-users/{bot_user_id}/token';
};

export type botsRevokeBotUserTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsRevokeBotUserTokenError = botsRevokeBotUserTokenErrors[keyof botsRevokeBotUserTokenErrors];

export type botsRevokeBotUserTokenResponses = {
    /**
     * Successful Response
     */
    200: BotUserPublic;
};

export type botsRevokeBotUserTokenResponse = botsRevokeBotUserTokenResponses[keyof botsRevokeBotUserTokenResponses];

export type botsIssueBotUserTokenData = {
    /**
     * Token In
     */
    body?: BotTokenIssue | null;
    path: {
        /**
         * Bot User Id
         */
        bot_user_id: string;
    };
    query?: never;
    url: '/api/v1/bot-users/{bot_user_id}/token';
};

export type botsIssueBotUserTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type botsIssueBotUserTokenError = botsIssueBotUserTokenErrors[keyof botsIssueBotUserTokenErrors];

export type botsIssueBotUserTokenResponses = {
    /**
     * Successful Response
     */
    200: BotTokenIssued;
};

export type botsIssueBotUserTokenResponse = botsIssueBotUserTokenResponses[keyof botsIssueBotUserTokenResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
